### ISSUE TITLE
Use Mozilla Public License instead MIT for Python SDK

### ISSUE THREAD

**Issue by Camilotk** [Open-Pix/python-sdk#4]
This issue aims to initiate a discussion regarding the potential adoption of the Mozilla Public License (MPL) for the Python SDK of Open PIX. Specifically, we will explore the advantages of MPL over the current licensing model, emphasizing the benefits of choosing an open-source license while clarifying that MPL does not impose restrictive obligations on users.

Points for discussion:

1. Licensing Comparison:
    While some projects within the Open PIX ecosystem are currently licensed under the MIT License, this discussion focuses on the possibility of switching to the Mozilla Public License (MPL) for the Python SDK. It is important to note that MPL, unlike viral licenses, does not impose restrictions on the use of the software. Users are still free to utilize the SDK under MPL without being obliged to disclose their own proprietary code or changes made to the SDK.

2. Advantages:
    The primary focus of this discussion is to highlight the benefits of embracing an open-source license such as the MPL for the Python SDK. By adopting MPL, we can leverage its permissive nature to foster collaboration around the SDK. The MPL offers a balanced approach that encourages innovation and allows commercial derivatives to be created based on the SDK without mandating the sharing of proprietary code.

What the Woovi opinion on it?

**Comment by sibelius** [comment]
it is not clear the differences

**Comment by Camilotk** [comment]
@sibelius:
> it is not clear the differences

The MIT License is a permissive license that allows anyone to use, modify, distribute, or sublicense the licensed code with very few restrictions. The only requirement is to include the original license and copyright notice in any copies or substantial portions of the code.

The MPL 2.0 is a weak copyleft license that allows anyone to use, modify, distribute, or sublicense the licensed code, but with some conditions1. The main condition is that any modifications to the code must be made available under the same license3. However, this does not apply to the entire application that uses the code, only to the files that contain the code. The MPL 2.0 also provides an explicit patent grant for using the code.

The main difference between the two licenses is that the MIT License does not require sharing any modifications to the code, while the MPL 2.0 does. The MPL 2.0 also offers more protection against patent claims than the MIT License. However, both licenses are compatible with other open source licenses and allow for commercial use of the code.

**Comment by Camilotk** [comment]
@sibelius:
> it is not clear the differences

**For the licenses**:
- The MIT License is a permissive license that allows anyone to use, modify, distribute, or sublicense the licensed code with very few restrictions. The only requirement is to include the original license and copyright notice in any copies or substantial portions of the code.
- The MPL 2.0 is a weak copyleft license that allows anyone to use, modify, distribute, or sublicense the licensed code, but with some conditions. The main condition is that any modifications to the code must be made available under the same license. However, this does not apply to the entire application that uses the code, only to the files that contain the code. The MPL 2.0 also provides an explicit patent grant for using the code.

**Differences**:

The main difference between the two licenses is that the MIT License does not require sharing any modifications to the code, while the MPL 2.0 does. The MPL 2.0 also offers more protection against patent claims than the MIT License. However, both licenses are compatible with other open source licenses and allow for commercial use of the code.

**Comment by Camilotk** [comment]
This was discussed in the Discord and opted out for MIT License.
